# based on the workflow of github.com/rubocop/rubocop
# Ref. https://github.com/rubocop/rubocop/blob/master/.github/workflows/spell_checking.yml
name: Spell Checking

on: [pull_request]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  codespell:
    name: Check spelling of all files with codespell
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: codespell-project/actions-codespell@v2
        with:
          check_filenames: true
          check_hidden: false
          ignore_words_file: .codespell

  misspell:
    name: Check spelling of all files in commit with misspell
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install
        run: wget -O - -q https://raw.githubusercontent.com/client9/misspell/master/install-misspell.sh | sh -s -- -b .
      - name: Misspell
        run: git ls-files --empty-directory | xargs ./misspell -i 'enviromnent' -error

